pipeline {
    agent any
    stages {
        stage("clean up") {
            steps{
                deleteDir()
            }
        }
        stage("clone repo") {
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install -Denforcer.skip=true"
                }
            }
        }
        stage("test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test -Denforcer.skip=true"
                }
            }
        }

        stage("remote") {
            steps {
                build job: 'boolean_Pipeline', parameters: [[$class: 'BooleanParameterValue', name:'myBoolean', value: true]]
            }
        }
    }
}