pipeline {
    agent any 

    parameters {
        booleanParam(
            defaultValue: false,
            description: "first bool parameter, let's play with that",
            name: "myBoolean",
        )
    }

    stages {
        stage("Demo") {
            steps {
                echo "booleanParam is set to: ${params.myBoolean}"
            }
        }
    }
}