pipeline {
    agent any 

    environment {
        def myString = "Hello World"
        def myNumber = 10
        def myBool = true 
    }

    stages{
        stage("Demo") {
            steps {
                echo "print myString ${myString}"
                echo "print myNumber ${myNumber}"
                echo "print myBool ${myBool}"

            }
        }
    }
}